version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3
  node: circleci/node@4.7.0

jobs:
  setup:
    docker:
      - image: cimg/ruby:2.7.5
    steps:
      - checkout
      - node/install:
          node-version: 16.13.0
          install-yarn: true
      - run: cp .circleci/database.yml config/database.yml
      - run: gem install bundler --conservative
      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run: bundle install -j4 --path ~/bundle
      - save_cache:
          paths: ~/bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-cache-{{ .Branch }}
            - v1-yarn-cache
      - run: yarn install
      - save_cache:
          paths: node_modules
          key: v1-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

  webpack:
    docker:
      - image: cimg/ruby:2.7.5
    environment:
      API_PATH: api
      ADMIN_PATH: admin
      ASSET_HOST: example.com
      DEFAULT_PER_PAGE: '30'
      DOMAIN_NAME: example.com
      MAX_PER_PAGE: '50'
      RAILS_ENV: test
      OHANA_API_ENDPOINT: http://ohana-api-test.herokuapp.com/api
      ELASTICSEARCH_URL: http://elastic:password@localhost:9200 # This gets set in chewy.rb file.
      ADMIN_APP_TOKEN: testing123
    steps:
      - checkout
      - node/install:
          node-version: 16.13.0
          install-yarn: true
      - run: cp .circleci/database.yml config/database.yml
      - run: gem install bundler --conservative
      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run: bundle install -j4 --path ~/bundle
      - save_cache:
          paths: ~/bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-cache-{{ .Branch }}
            - v1-yarn-cache
      - run: yarn install
      - save_cache:
          paths: node_modules
          key: v1-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: RAILS_ENV=test bundle exec rails webpacker:compile

  specs:
    resource_class: medium
    docker:
      - image: cimg/ruby:2.7.5
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:12-postgis
        environment:
          POSTGRES_DB: ohana_api_test
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: elasticsearch:7.17.0
        environment:
          ELASTIC_PASSWORD: password
          discovery.type: single-node
          xpack.security.enabled: true
    environment:
      API_PATH: api
      ADMIN_PATH: admin
      ASSET_HOST: example.com
      DEFAULT_PER_PAGE: '30'
      DOMAIN_NAME: example.com
      MAX_PER_PAGE: '50'
      RAILS_ENV: test
      OHANA_API_ENDPOINT: http://ohana-api-test.herokuapp.com/api
      ELASTICSEARCH_URL: http://localhost:9200 # This gets set in chewy.rb file.
      ADMIN_APP_TOKEN: testing123
    steps:
      - checkout
      - node/install:
          node-version: 16.13.0
          install-yarn: true
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: cp .circleci/database.yml config/database.yml
      - run: gem install bundler --conservative
      - run: sudo apt-get update -qq && sudo apt-get install -y postgresql-client
      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run: bundle install -j4 --path ~/bundle
      - save_cache:
          paths: ~/bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v1-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-cache-{{ .Branch }}
            - v1-yarn-cache
      - run: yarn install
      - save_cache:
          paths: node_modules
          key: v1-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: dockerize -wait tcp://localhost:9200 -timeout 1m
      - run: ./bin/rails db:drop db:create db:migrate
      - run: bundle exec rspec --format documentation --color

workflows:
  setup-lint-test:
    jobs:
      - setup
      - webpack:
          requires:
            - setup
      - specs:
          requires:
            - setup

